[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2021"
name = "deno-lint"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
annotate-snippets = {version = "0.9", features = ["color"]}
anyhow = "1"
deno_ast = "0.5.0"
deno_lint = "0.19.0"
env_logger = "0.9"
global_alloc = {path = "../../crates/alloc"}
globwalk = "0.8"
ignore = "0.4"
napi = {version = "1", features = ["serde-json"]}
napi-derive = "1"
serde = "1"
serde_json = "1"

[build-dependencies]
napi-build = "1"
