[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2021"
name    = "deno-lint"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
annotate-snippets = { version = "0.9", features = ["color"] }
anyhow            = "1"
deno_ast          = "=0.29.5"
deno_lint         = "=0.51.0"
env_logger        = "0.10"
global_alloc      = { path = "../../crates/alloc" }
globwalk          = "0.8"
ignore            = "0.4"
miette            = { version = "5", features = ["fancy-no-backtrace"] }
napi              = { version = "2", default-features = false, features = ["napi3"] }
napi-derive       = { version = "2" }
serde             = "1"
serde_json        = "1"

[build-dependencies]
napi-build = "2"
