[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2018"
name = "deno-lint"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
annotate-snippets = {version = "0.9", features = ["color"]}
ast_view = {version = "0.33.1", package = "dprint-swc-ecma-ast-view"}
deno_lint = "=0.14.0"
ignore = "0.4"
napi = {version = "1", features = ["serde-json"]}
napi-derive = "1"
serde = "1"
serde_json = "1"
swc_ecmascript = {version = "=0.63.0", features = ["parser", "transforms", "utils", "visit"]}

[target.'cfg(all(target_arch = "x86_64", not(target_env = "musl")))'.dependencies]
mimalloc = {version = "0.1"}

[build-dependencies]
napi-build = "1.1.0"
