[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2021"
name = "node-rs-jieba"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
global_alloc = {path = "../../crates/alloc"}
jieba-rs = {version = "0.6", features = ["default-dict", "tfidf", "textrank"]}
napi = {version = "2"}
napi-derive = {version = "2"}
once_cell = "1.8"

[build-dependencies]
napi-build = "1"
