[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2018"
name = "node-rs-jieba"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
jieba-rs = {version = "0.6", features = ["default-dict", "tfidf", "textrank"]}
napi = "1"
napi-derive = "1"
once_cell = "1.5"

[target.'cfg(all(unix, not(target_env = "musl"), not(target_os = "freebsd"), not(target_arch = "arm"), not(target_arch = "aarch64")))'.dependencies]
jemallocator = {version = "0.3", features = ["disable_initial_exec_tls"]}

[target.'cfg(all(windows, not(target_arch = "aarch64")))'.dependencies]
mimalloc = {version = "0.1"}

[build-dependencies]
napi-build = "1.1.0"
