[package]
authors = ["Francesco Benedetto"]
edition = "2024"
name = "node-rs-jsonwebtoken"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
global_alloc = { workspace = true }
indexmap = { workspace = true, features = ["serde"] }
jsonwebtoken = { workspace = true }
napi = { workspace = true, default-features = false, features = ["napi3", "serde-json-ordered", "object_indexmap"] }
napi-derive = { workspace = true }
rand_core = { version = "0.10" }
serde = { workspace = true }
serde_json = { workspace = true }

[build-dependencies]
napi-build = { workspace = true }
