[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2021"
name = "xxhash"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
global_alloc = {path = "../../crates/alloc"}
napi = {version = "2", default-features = false, features = ["napi6"]}
napi-derive = {version = "2"}
xxhash-rust = {version = "0.8", features = ["xxh32", "xxh64", "xxh3"]}

[build-dependencies]
napi-build = "1"
