[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+sse4.2"]
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+sse4.2"]
[target.x86_64-apple-darwin]
rustflags = ["-C", "target-feature=+sse4.2"]
[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"
rustflags = ["-C", "target-feature=-crt-static"]
